Remove kano dependencies
KanoComputing/pydevtools pull request #30
Opened 2017-01-11 17:44 UTC by skarbat

Should cover #24  - @tombettany

2017-01-11 17:46 UTC, pazdera commented on pydevtools/profiling_late.py
> +# Copyright (C) 2017 Kano Computing Ltd.
I think this should be `2015, 2017`

2017-01-11 17:48 UTC, tombettany requested changes

2017-01-11 17:48 UTC, tombettany commented on pydevtools/profiling_late.py
> +# Copyright (C) 2017 Kano Computing Ltd.
Should this cover 2015 too?

2017-01-11 17:48 UTC, tombettany commented on pydevtools/profiling.py
> +defaultConf = {
This is a constant so I think that it should be `DEFAULT_CONF`

2017-01-11 17:48 UTC, tombettany commented on pydevtools/profiling.py
> +        profiling_late.declare_timepoint(name, isStart)
Can we make this parameter `is_start`?

2017-01-11 17:48 UTC, tombettany commented on pydevtools/profiling.py
>  '''
Do we need an update to the copyright here?

2017-01-11 17:54 UTC, gpgabriel commented on pydevtools/profiling_late.py
> +                        print 'Stop profiling for point "{0}" and do "{1}" instead'.format(point_current, name)
Small thing here: as Python 2 has an expiration date, maybe it would be a good idea to use the print format from Python 3. Other than that 👍

2017-01-18 17:29 UTC, tombettany approved these changes

2017-01-18 17:29 UTC, merged